Repository surendratalk/html-portfolio, pull requests merged in 2022-10, with the labels that each got.

#1 Created a basic portfolio site using html only.
  index.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#2 Create new-index.html
  new-index.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#3 Create coming-soon.html
  coming-soon.html
Labels: help wanted, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#4 Create developer-portfolio.html
  developer-portfolio.html
Labels: help wanted, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#5 Create try.html
  try.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#7 Create newpage.html
  newpage.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#8 Create page-portfolio.html
  page-portfolio.html
Labels: help wanted, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#10 Create mainpage.html
  mainpage.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#11 Create new-port.html
  new-port.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#12 Create template-single.html
  template-single.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022
